### PR TITLE
Ansible deployments

### PR DESCRIPTION
**Pull request by powellc**
A really simple playbook for setting up pypicloud using ansible. I can docs if you have any interest in this.

### CODE REVIEW

**Comment by stevearc** [comment]
This is great! Question: do projects typically include ansible playbooks in the same repository? My instinct would be to put it in a separate repo so the versions aren't tied together, but I'm willing to go with whatever the common practice is. Also, it seems like there's a bunch of stuff in there that's unrelated to pypicloud (all the UFW commands, the `info.html` page, etc). For anything in the main pypicloud repo I'd prefer it to be trimmed down to just the relevant bits, to make it easier to skim and twiddle. Thoughts?

**Comment by powellc** [comment]
Hmm, good question. Some projects break it out, and some drop them in. As I think in it, it might be better to have an ansible-pypicloud repository. That would also explain the reason for things likw UFW and what-not.

Basically you can point the ansible script at a vanilla Ubuntu/Debian VPS and it will setup a running pypicloud instance. In order to do that, there are some housekeeping things Ansible needs to do like set timezones properly, and setup a firewall.

I'll setup a parallel repository on Github for the ansible scripts and you can close this baby down. References to the ansible build are welcome too :)

**Comment by powellc** [comment]
Here we go: https://github.com/powellc/ansible-pypicloud

**Comment by stevearc** [comment]
Great! I added a reference [in the docs](https://github.com/mathcamp/pypicloud/commit/c63af0fd128b849db5a23408f0c508fb51b5db89) that will get pushed out once I cut a new release (coming Soon&trade;)

**Comment by powellc** [comment]
Awesome. Thanks for a great project!

CP

**Pull request closed without merging**
